//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperZapatos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Articles
    {
        /// <summary>
        /// Entity Primary key.
        /// </summary>
        public int id { get; set; }

        /// <summary>
        /// Article name.
        /// </summary>
        [Display(Name = "Articulo")]
        [Required(ErrorMessage = "Campo obligatorio")]
        public string name { get; set; }

        /// <summary>
        /// Article description.
        /// </summary>
        [Display(Name = "Descripción")]
        [Required(ErrorMessage = "Campo Obligatorio")]
        public string description { get; set; }

        /// <summary>
        /// Article price.
        /// </summary>
        [Display(Name = "Precio")]
        [Required(ErrorMessage = "Campo obligatorio")]
        [Range(0.0, Double.MaxValue, ErrorMessage = "Precio no válido.")]
        public decimal price { get; set; }

        /// <summary>
        /// Units in shelf. 
        /// </summary>
        [Display(Name = "En repisa")]
        [Required(ErrorMessage = "Campo obligatorio")]
        [Range(0, int.MaxValue, ErrorMessage = "Ingrese un número válido")]
        public int total_in_shelf { get; set; }

        /// <summary>
        /// Units in vault.
        /// </summary>
        [Display(Name = "En bodega")]
        [Required(ErrorMessage = "Campo obligatorio")]
        [Range(0, int.MaxValue, ErrorMessage = "Ingrese un número válido")]
        public int total_in_vault { get; set; }

        /// <summary>
        ///  Store related.
        /// </summary>
        [Display(Name = "ID tienda")]
        [Required(ErrorMessage = "Campo obligatorio")]
        public int store_id { get; set; }
        
        public virtual Stores Stores { get; set; }
    }
}
