//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperZapatos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Stores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stores()
        {
            this.Articles = new HashSet<Articles>();
        }
    
        /// <summary>
        /// Entity primary key.
        /// </summary>
        [Display(Name = "ID")]
        public int id { get; set; }
        
        /// <summary>
        /// Store name.
        /// </summary>
        [Display(Name = "Tienda")]
        [Required(ErrorMessage = "Campo obligatorio")]
        public string name { get; set; }

        /// <summary>
        /// Store address.
        /// </summary>
        [Display(Name = "Dirección")]
        [Required(ErrorMessage = "Campo obligatorio")]
        public string address { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Articles> Articles { get; set; }
    }
}
